name: ScreenCapLibrary CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]
        python-version: [ 2.7, 3.8, 3.9 ]
        include:
          - os: ubuntu-latest
            set_display: export DISPLAY=:99; Xvfb :99 -screen 0 800x600x24 -ac -noreset & sleep 3

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} with Robot Framework ${{ matrix.rf-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Install dependencies for Python 2
        if: matrix.python-version == '2.7' && runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt install xvfb
      #   sudo apt install -y python-gtk2
      - name: Install dependencies for Python 3
        if: matrix.python-version != '2.7' && runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt install xvfb python-gi python-gi-cairo python3-gi python3-gi-cairo gir1.2-gtk-3.0 libgirepository1.0-dev
          pip install PyGObject
      - name: Run tests with Python 2.7 on Linux
        if: matrix.python-version == '2.7' && runner.os == 'Linux'
        run: |
          ${{ matrix.set_display }}
          python atest/run.py -e gtk -e no-xvfb atest
      - name: Run tests with Python 3 on Linux
        if: matrix.python-version != '2.7' && runner.os == 'Linux'
        run: |
          ${{ matrix.set_display }}
          python atest/run.py -e no-xvfb atest
      - name: Run tests on Windows/MacOS
        if: runner.os != 'Linux'
        run: |
          python atest/run.py -e gtk atest
      - uses: actions/upload-artifact@v1
        if: success() || failure()
        with:
          name: Test Results - Python ${{ matrix.python-version }} ${{ runner.os }}
          path: atest/results/
